services:
  server:
    build:
      context: ..
      dockerfile: e2e/Dockerfile.e2e
    privileged: true
    networks:
      - proxyfoxy
    volumes:
      - shared:/shared
    command: ["/e2e/two-container-server.sh"]

  provider:
    build:
      context: ..
      dockerfile: e2e/Dockerfile.e2e
    networks:
      - proxyfoxy
    volumes:
      - shared:/shared
    depends_on:
      - server
    command: ["/e2e/two-container-provider.sh"]

networks:
  proxyfoxy:

volumes:
  shared:
